Remove duplicate $ssl_interface
This was added twice in two separate pull requests and
causes the following error:

Error: Cannot reassign variable ssl_interface at /etc/puppet/modules/rabbitmq/manifests/config.pp:35